language: php
php:
  - 5.6
install:
  - composer install --dev --no-interaction
before_script:
  - echo 'date.timezone = "Australia/Sydney"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - mysql -e 'create database wtrack_test;'
  - composer test:rebuild-db
  - mkdir -p build/logs
script:
  - phpunit -c app --coverage-clover build/logs/clover.xml
after_script:
  - php vendor/satooshi/php-coveralls/composer/bin/coveralls -v
