language: php
php:
  - 5.6
install:
  - composer install
before_script:
  - echo 'date.timezone = "Australia/Sydney"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - mysql -e 'create database wtrack_test;'
  - composer test:rebuild-db
script:
  - phpunit -c app
