language: php
php:
  - 5.6
install:
  - composer install
before_script:
  - phpenv config-add myconfig.ini
  - mysql -e 'create database wtrack_test;'
  - composer test:rebuild-db
script:
  - phpunit -c app
